services:
  postgres:
    image: postgres:latest
    container_name: postgres_bd_quadropresenca
    restart: always
    environment:
      POSTGRES_DB: bd_quadropresenca
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: